### ISSUE TITLE
How can specify an instance name?

### ISSUE THREAD

**Issue by athoune** [xcir/python-varnishapi#15]
I'm using multiple Varnish named instances.

Here is the crash test with the latest version of the API, using Debian Jessie and its python 2.7.9
```
>>> import varnishapi
>>> vsc = varnishapi.VarnishStat(opt='-n translation')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "varnishapi.py", line 372, in __init__
    self.__setArg(opt)
  File "varnishapi.py", line 383, in __setArg
    if self.__r_arg and self.vsm:
AttributeError: VarnishStat instance has no attribute '_VarnishStat__r_arg'
```

**Comment by xcir** [comment]
Thank you for your bug report!
